/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizzappswings;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.NoSuchElementException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Lava Kumar
 */
public class Quizzstarts extends javax.swing.JFrame {

    /**
     * Creates new form Quizzstarts
     */
    public Quizzstarts() {
            
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        txtRollno = new javax.swing.JTextField();
        lblroll = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaQuestion = new javax.swing.JTextArea();
        txtOption = new javax.swing.JTextField();
        lbloption = new javax.swing.JLabel();
        lbl1st = new javax.swing.JLabel();
        txtExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(204, 255, 204));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quizz Starts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        labelName.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 102, 0));
        labelName.setText("Name of me");

        btnNext.setBackground(new java.awt.Color(204, 204, 255));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNext.setForeground(new java.awt.Color(0, 0, 204));
        btnNext.setText("Start");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(204, 204, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(0, 0, 153));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtRollno.setBackground(new java.awt.Color(204, 204, 255));

        lblroll.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        lblroll.setForeground(new java.awt.Color(102, 153, 0));
        lblroll.setText("Enter RollNumber:");

        TextAreaQuestion.setColumns(20);
        TextAreaQuestion.setRows(5);
        jScrollPane1.setViewportView(TextAreaQuestion);

        lbloption.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbloption.setForeground(new java.awt.Color(51, 102, 0));
        lbloption.setText("Enter option(a,b,c,d):");

        lbl1st.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl1st.setForeground(new java.awt.Color(204, 0, 0));
        lbl1st.setText("For 1st Question Press Start");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addContainerGap(223, Short.MAX_VALUE)
                                        .addComponent(btnNext)
                                        .addGap(77, 77, 77)
                                        .addComponent(btnSubmit))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addComponent(lbl1st)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblroll)))
                                .addGap(1, 1, 1))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtRollno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lbloption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOption, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelName))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblroll)
                            .addComponent(lbl1st))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbloption)
                    .addComponent(txtOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnSubmit))
                .addContainerGap())
        );

        txtExit.setBackground(new java.awt.Color(255, 102, 0));
        txtExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtExit.setText("Exit");
        txtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtExit)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExit)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExitActionPerformed
            System.exit(0); 
       
            
    }//GEN-LAST:event_txtExitActionPerformed
 int result=-1;
 String RollNo;
 int total=0;
 Scanner scan,scanAns;
int current=0;
BufferedReader bread;
BufferedReader bAns;
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        lbl1st.setText("Lets starts Quiz...");
        btnNext.setText("Next");
        if(current==0)
       { 
        FileReader fread=null;
        FileReader fAns=null;
        try {
            fread = new FileReader("Questions.txt");
            fAns=new FileReader("Answers.txt");
            bread=new BufferedReader(fread);
            bAns=new BufferedReader(fAns);
             String n=bread.readLine();
             scan=new Scanner(bread);
             scanAns=new Scanner(bAns);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReadFileNew.class.getName()).log(Level.SEVERE, null, ex);
        }  catch (IOException ex) {
               Logger.getLogger(ReadFileNew.class.getName()).log(Level.SEVERE, null, ex);
           }     
     current++;  
       }
         if(scan!=null)
            {
                scan.useDelimiter("#");
                if(scan.hasNextLine())
                {
                    TextAreaQuestion.setText(scan.next()+"\n");
                   
                }
            }
         try
         {
          if(scanAns!=null)
           {
               
           String option =this.txtOption.getText();
           String check=scanAns.findInLine(option);
           //System.out.println("option  and check  "+option+"  "+check);
           if(option.equals(check))
           {
               result=result+1;
           }
          scanAns.nextLine();
          total++;
         } 
          txtOption.setText("");
         }catch(NoSuchElementException e)
         {
             txtOption.setText("");
             btnNext.setEnabled(false);
            // System.out.println("elemneets over"); 
         }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        System.out.println("Hello"+txtRollno.getText());
        if(txtRollno.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"RollNumber is Blanked Please enter a Valid RollNumber");
        }
        if(txtRollno.getText().length()<12)
        {
            JOptionPane.showMessageDialog(null,"Please enter a Valid RollNumber contains 12 digits");
        }
        else
        {
        ResultDisplay resultobj=new ResultDisplay();  
         FileWriter fstu;
         FileReader fClass;
        try {
            fstu = new FileWriter("StudentsResult.txt",true);
             BufferedWriter bstu = new BufferedWriter(fstu);
             fClass= new FileReader("TotalClass.txt");
		BufferedReader bClass=new BufferedReader(fClass);
            
            RollNo=this.txtRollno.getText();
            System.out.println(RollNo);
            String CheckNo;
            int flag=0;
            while((CheckNo=bClass.readLine())!=null)
            {
                if(CheckNo.contains(RollNo))
                {
                    flag=1;
                    break;
                }
            }
            if(flag==1)
            {
                RollNo=CheckNo;
            }
            String StudentResultStore=(CheckNo+"   :   "+result);
            bstu.append(StudentResultStore);
            bstu.newLine();
            bstu.close();
        ResultDisplay.lblResult.setText("your  total Score is="+result+"  Out of  "+total+" \n Congratulations......."+RollNo);
        
            resultobj.setVisible(true);
                        setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Quizzstarts.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        }		
    }//GEN-LAST:event_btnSubmitActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quizzstarts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quizzstarts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quizzstarts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quizzstarts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quizzstarts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaQuestion;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel labelName;
    private javax.swing.JLabel lbl1st;
    private javax.swing.JLabel lbloption;
    private javax.swing.JLabel lblroll;
    private javax.swing.JPanel panel;
    private javax.swing.JButton txtExit;
    private javax.swing.JTextField txtOption;
    private javax.swing.JTextField txtRollno;
    // End of variables declaration//GEN-END:variables

   
}
